### ISSUE TITLE
DataflowMethod() returns empty result

### ISSUE THREAD

**Issue by RodionQNX** [mingjerli/IMFData#14]
DataflowMethod() returns empty value. At the same time other functions, like DataStructureMethod() work fine. What could be the problem?

**Comment by davdigioia** [comment]
library(IMFData)
availableDB <- DataflowMethod()

I get the Following Error

Error: lexical error: invalid char in json text.
                                       <?xml version="1.0" encoding="u
                     (right here) ------^
In addition: Warning message:
 Show Traceback
 
 Rerun with Debug
 Error: lexical error: invalid char in json text.
                                       <?xml version="1.0" encoding="u
                     (right here) ------^ 

Anyone has some idea?

**Comment by ghost** [comment]
I also have the same problem. 

I use: 

`DataflowMethod()
`


and then: 

```
No encoding supplied: defaulting to UTF-8.
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^
In addition: Warning message:
 Show Traceback
 
 Rerun with Debug
 Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^ 
```

**Comment by bccarneiro** [comment]
Same error as you. Any idea?

No encoding supplied: defaulting to UTF-8.
 Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//W3C//
                     (right here) ------^ 
In addition: Warning message:
JSON string contains (illegal) UTF8 byte-order-mark!

**Comment by winteraspect** [comment]
I remember the method is not universal for all datasets. So I forked this pkg and rewrote the dataflowmethod. There is also a logic error in the compactflowmethod. Allow me some time and I will commit my revision soon. Though I cannot guarantee it applies to every situation.

**Comment by pvillaparo** [comment]
hi, anybody discovered how to solve the problem?

**Comment by mingjerli** [comment]
I think I just found the solution, PR merged.

**Comment by maxwqx** [comment]
I still encounter the same problem.
